name: EverythingShop Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '21.x'
      - name: Run install
        run: npm install --legacy-peer-deps
      - name: Run build
        run: npm run build
      - name: Run test
        run: npm run test-cli
